'use client';
import EvidencePreview from '../EvidencePreview';
import {useEffect,useState,useRef} from 'react';
export default function MockPortal(){
 const [c,setC]=useState<any>(null),[error,setError]=useState(''),[result,setResult]=useState(''),[approved,setApproved]=useState(false),[busy,setBusy]=useState(false);
 const revision=useRef<number|null>(null);
 useEffect(()=>{const id=new URLSearchParams(location.search).get('case');if(!id){setError('Open this form from a reviewed Grievance Clock case.');return;}let active=true;async function refresh(){try{const r=await fetch('/api/cases/'+encodeURIComponent(id!));if(!r.ok)throw Error('This complaint is unavailable or has been deleted.');const next=await r.json();if(active){if(revision.current!==next.revision)setApproved(false);revision.current=next.revision;setC(next);setError('');}}catch(e){if(active){setC(null);setError((e as Error).message);}}}void refresh();const timer=setInterval(refresh,5000);window.addEventListener('focus',refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',refresh);};},[]);

 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`/api/cases/${c.id}/simulate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approved,revision:c.revision,idempotency_key:crypto.randomUUID()})});const j=await r.json();if(!r.ok)throw Error(j.detail);setResult(j.filings.at(-1).reference_number);}catch(e){setError((e as Error).message);}finally{setBusy(false)}}
 return <main className="mock-page"><div className="eyebrow">GRIEVANCE CLOCK · FILING PREVIEW</div><h1>Complaint filing preview</h1><p>Review your prepared complaint and attachments here. This preview does not submit anything to an organisation or regulator.</p>{error&&<div className="error" role="alert">{error}</div>}{result?<section className="card"><h2>Simulated acknowledgement</h2><strong data-testid="reference">{result}</strong><p>No complaint was sent to a regulator. The example timeline is now visible in Grievance Clock.</p><a href="/">Return to your workspace</a></section>:c&&<form onSubmit={submit}><label>Case reference<input aria-label="Case reference" readOnly value={c.id}/></label><label>Entity<input aria-label="Entity" readOnly value={c.facts.entity_name||'Not provided'}/></label><label>Prepared complaint<textarea aria-label="Prepared complaint" readOnly rows={12} value={c.draft||'Confirm facts in the assistant first.'}/></label><label>Evidence index<textarea aria-label="Evidence index" readOnly rows={3} value={c.evidence.map((e:any)=>e.name+' · SHA-256 '+e.sha256).join('\n')||'No attachments'}/></label><EvidencePreview caseId={c.id} evidence={c.evidence}/><label className="checkbox"><input style={{width:'auto'}} type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>I approve this simulated submission</label><button className="primary" disabled={!approved||!c.facts_confirmed||busy||c.status==='resolved'}>Submit simulation</button></form>}</main>
}
